sudo: false
language:
- node_js
node_js:
- "6"
script:
- npm test
- cd examples
    && npm install
    && node_modules/.bin/elm-package install -y
    && npm test
    && node_modules/.bin/elm-make Example.elm
